version: '3'
services:
  wordpress:
    depends_on:
      - db
    build:
      context: .
      dockerfile: docker/wordpress/Dockerfile
    restart: always
    volumes:
      - ./wp-content:/var/www/html/wp-content 
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    hostname: web.local
    ports:
      - 80:80 
      - 443:443
    networks:
      back:
        aliases:
          - web.local
    hostname: web.local
  db:
    image: mysql:5.7
    restart: always
    volumes:
       - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: p4ssw0rd!
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - 3306:3306 
    networks:
      - back
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    hostname: phpmyadmin.local
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: p4ssw0rd!
    networks:
      back:
        aliases:
          - phpmyadmin.local
networks:
  back:
    driver: bridge
volumes:
  db_data: